### ISSUE TITLE
Inconsistent Function Naming

### ISSUE THREAD

**Issue by IXLLEGACYIXL** [VaclavElias/stride-docs-next#15]
Powershell follows the Standard for function names like the following
```
[VERB]-[NOUN]
[VERB]-[NOUN][NOUN]
[VERB]-[NOUN][NOUN][NOUN][NOUN]
```
having 3 nouns is uncommon but also acceptable and often used.
There is also the Powershell command `Get-Verb` to see the "standard verbs" that should be used if possible.
For instance Run is not a common verb, Start is better.
But for some Situations like "Ask" there is no Verb, so its fine. In that case a Company would extend the Verbs in Get-Verb
So Get-Verb is more a "Guideline" than a rule ( i dont follow it either .. i try to use them as best as possible ).

`Start-LogTranscript` this is a correct Function Name
`GetUserInput` this is a wrong function name it should be `Get-UserInput`
`RunLocalWebsite` this is also a wrong function name it should be `Start-LocalWebsite` as Run is Uncommon

**Comment by VaclavElias** [comment]
If you would like, you can make these name updates and create PR?
